do $$ declare t text; begin for t in select tablename from pg_tables where schemaname='public' loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create or replace function is_admin() returns boolean language sql stable as $$ select exists(select 1 from admin_users where email=auth.jwt()->>'email' and status='active' and role in('staff','admin','owner')) $$;
create or replace function is_owner() returns boolean language sql stable as $$ select exists(select 1 from admin_users where email=auth.jwt()->>'email' and status='active' and role='owner') $$;
insert into admin_users(email,role,status) values ('anoop.anoops@gmail.com','owner','active'),('sindhug84@gmail.com','owner','active') on conflict(email) do update set role='owner',status='active';
insert into admin_settings(key,value) values ('kitchen_location','{"lat":8.5241,"lng":76.9366}'::jsonb),('default_cutoff_time','"20:00"'::jsonb) on conflict(key) do nothing;
insert into dish_categories(name,sort_order) values ('Salads',1),('Kanji',2),('Breakfast',3),('Chapati Meals',4),('Protein Add-ons',5),('Healthy Desserts',6),('Drinks',7),('Snacks',8),('Subscription Bowls',9),('Uncategorized',99) on conflict(name) do nothing;
insert into plan_aliases(alias,plan_display_name,variant_name) values ('Weightloss','Weight Loss',null),('Elite-Veg Plan-Lunch','Elite Plan-Lunch','Veg'),('Elite-Non-Veg Plan-Dinner','Elite Plan-Dinner','Non-Veg'),('Smoothie + Gut Booster Plan','Smoothie Plan',null),('Elite Plan-DInner','Elite Plan-Dinner',null) on conflict(alias) do nothing;
-- Baseline permissive public read/admin write policies for phase-1; tighten per environment as needed.
do $$ declare t text; begin for t in select tablename from pg_tables where schemaname='public' loop execute format('drop policy if exists public_read on public.%I',t); execute format('create policy public_read on public.%I for select using (true)',t); execute format('drop policy if exists admin_write on public.%I',t); execute format('create policy admin_write on public.%I for all using (is_admin()) with check (is_admin())',t); end loop; end $$;
